stm8/
	;------------------------------------------------------
	; SEGMENT MAPPING FILE AUTOMATICALLY GENERATED BY STVD
	; SHOULD NOT BE MANUALLY MODIFIED.
	; CHANGES WILL BE LOST WHEN FILE IS REGENERATED.
	;------------------------------------------------------
	BYTES			; The following addresses are 8 bits long
	segment byte at 0-FF 'ram0'

	WORDS			; The following addresses are 16 bits long
	segment byte at 100-DFE 'ram1'

	WORDS			; The following addresses are 16 bits long
	segment byte at DFF-FFF 'stack'

	WORDS			; The following addresses are 16 bits long
	segment byte at 1000-17FF 'eeprom'

	WORDS			; The following addresses are 16 bits long
	segment byte at 8080-17FFF 'rom'

	WORDS			; The following addresses are 16 bits long
	segment byte at 8000-807F 'vectit'

		END
